name: square_bishop
description: A bridge package between Squares and Bishop, simplifying common uses.
version: 0.2.14
homepage: https://github.com/alexobviously/squares

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bishop: ^1.2.9
  equatable: ^2.0.3
  squares: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0